"use client";

import { Card, CardContent } from "@/components/ui/card";
import {
  MessageSquare,
  Zap,
  ArrowUpRight,
  ArrowDownLeft,
  Database,
  DollarSign,
  Cpu,
  Users,
} from "lucide-react";

type TimeRange = "daily" | "weekly" | "monthly";

interface SummaryProps {
  summary: {
    totalSessions: number;
    totalUserTurns: number;
    totalAssistantTurns: number;
    totalTokens: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    totalCacheRead: number;
    totalCacheWrite: number;
    totalCost: number;
    modelsUsed: number;
    providersUsed: number;
  };
  timeRange?: TimeRange;
}

function formatTokens(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

function formatCost(cost: number): string {
  if (cost === 0) return "$0.00";
  if (cost < 0.01) return `$${cost.toFixed(4)}`;
  return `$${cost.toFixed(2)}`;
}

const TIME_RANGE_LABELS: Record<TimeRange, string> = {
  daily: "All Days",
  weekly: "All Weeks",
  monthly: "All Months",
};

export function SummaryCards({ summary, timeRange = "daily" }: SummaryProps) {
  const cards = [
    {
      label: "Total Tokens",
      value: formatTokens(summary.totalTokens),
      icon: Zap,
      description: "Across all sessions",
      accent: "text-chart-1",
    },
    {
      label: "Input Tokens",
      value: formatTokens(summary.totalInputTokens),
      icon: ArrowUpRight,
      description: "Sent to models",
      accent: "text-chart-2",
    },
    {
      label: "Output Tokens",
      value: formatTokens(summary.totalOutputTokens),
      icon: ArrowDownLeft,
      description: "Generated by models",
      accent: "text-chart-3",
    },
    {
      label: "Cache Read",
      value: formatTokens(summary.totalCacheRead),
      icon: Database,
      description: "Tokens from cache",
      accent: "text-chart-4",
    },
    {
      label: "Total Cost",
      value: formatCost(summary.totalCost),
      icon: DollarSign,
      description: "API costs",
      accent: "text-chart-5",
    },
    {
      label: "Sessions",
      value: summary.totalSessions.toString(),
      icon: MessageSquare,
      description: `${summary.totalUserTurns} user / ${summary.totalAssistantTurns} assistant turns`,
      accent: "text-chart-1",
    },
    {
      label: "Models",
      value: summary.modelsUsed.toString(),
      icon: Cpu,
      description: "Unique models used",
      accent: "text-chart-2",
    },
    {
      label: "Providers",
      value: summary.providersUsed.toString(),
      icon: Users,
      description: "API providers",
      accent: "text-chart-4",
    },
  ];

  return (
    <div className="space-y-2">
      {timeRange && (
        <p className="text-xs text-muted-foreground">
          Showing totals for: <span className="font-medium text-foreground">{TIME_RANGE_LABELS[timeRange]}</span>
        </p>
      )}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {cards.map((card) => (
        <Card key={card.label}>
          <CardContent className="pt-5 pb-4 px-5">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                {card.label}
              </span>
              <card.icon className={`h-4 w-4 ${card.accent}`} />
            </div>
            <div className="text-2xl font-bold tracking-tight">{card.value}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {card.description}
            </p>
          </CardContent>
        </Card>
      ))}
      </div>
    </div>
  );
}
